### ISSUE TITLE
Eric

### ISSUE THREAD

**Issue by ericclose** [ericclose/comments#20]
https://ericclose.github.io/friends/ 

 
友链

**Comment by ericclose** [comment]
## 测试留言

```yaml
- name: Eric
  avatar: https://avatars1.githubusercontent.com/u/34526560?s=400&u=2d958bf7de727babbd13351a7db934f672169281&v=4
  url: https://ericclose.github.io
  backgroundColor: '#3E74C9'
  textColor: '#fff'
  tags: [计算机, 萌新]
  desc: To be completed...
```
