### ISSUE TITLE
 - Eric

### ISSUE THREAD

**Issue by ericclose** [ericclose/comments#22]
https://ericclose.github.io/friends/

**Comment by ericclose** [comment]
## 留言示例

```yaml
    - name: ericclose
      avatar: https://cdn.jsdelivr.net/gh/ericclose/cdn-assets/img/avatar.jpeg
      url: https://ericclose.github.io
      backgroundColor: '#3E74C9'
      textColor: '#fff'
      tags: [计算机, 小白]
      desc: Never give up!
```
