### ISSUE TITLE
友链 - Eric

### ISSUE THREAD

**Issue by ericclose** [ericclose/comments#23]
https://ericclose.github.io/friends/ 

 
友链

**Comment by ericclose** [comment]
## 评论示例

```yaml
- name: Eric
  avatar: https://cdn.jsdelivr.net/gh/ericclose/cdn-assets/img/avatar.jpeg
  url: https://ericclose.github.io
  backgroundColor: '#3E74C9'
  textColor: '#fff'
  tags: [计算机, 萌新]
  desc: To be completed...
```
